### ISSUE TITLE
Unable to export it for the Quest3

### ISSUE THREAD

**Issue by Fabryz** [Nitwel/Immersive-Home#42] opened 2023-11-21 14:38 UTC
Hi Nitwel,
I know this isn't actually related to your code, but I need a hand on making this work, maybe you have already had this issue and know what's wrong.
Searching through the internet brings to nothing helpful, asking to chatGPT just is not helpful too :p
I'm trying to wrap my head around this...

---

I have followed the guide here: https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html

- installed the OpenJDK (the v17 at first, then the v11 because someone else was having my issue and went back to 11)
- installed the Android Studio with Android SDK (yeah I could have installed only the latter, but I just wanted to make this damn thing work and follow step by step.
- made sure the required dependencies were installed:
    - Android SDK Build tools 34
    - Android SDK Platform-tools 34
    - NDK (side by side)
    - Android SDK command line tools (latest) 
    - CMake
    - Android Emulator 32
- created the debug.keystore and set it under the .android folder
- updated the Android SDK path and debug.keystore path on Godot IDE
    
![image](https://github.com/Nitwel/Immersive-Home/assets/17748/b64c41bc-84e5-40f4-a392-1f047da4966f)
( I actually now downgraded the versions to the ones suggested on the documentation)

When I launched the remote debug on Quest 3 it tells me:

```
Could not find version of build tools that matches Target SDK, using 34.0.0
0 param: --xr_mode_openxr
1 param: --use_immersive
  editor/export/editor_export_platform.h:178 - Esporta: Compilazione del progetto Android fallita, controlla l'output per vedere gli errori. In alternativa, visita docs.godotengine.org per la documentazione della build Android.
  Cannot remove non-existent file or directory: /Users/fabryz/Library/Caches/Godot/tmpexport.1700564252.apk
```
Translated: _"Export: Android project compilation failed, check the output for errors. Alternatively, visit docs.godotengine.org for Android build documentation."_

More output from the gradlew tasks command:
```
~/Sites/fabryz/Immersive-Home/android/build  main ?11 
╰─ ./gradlew tasks

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/fabryz/Immersive-Home/android/build/settings.gradle'

* What went wrong:
Could not compile settings file '/Users/fabryz/Immersive-Home/android/build/settings.gradle'.
> startup failed:
  General error during conversion: Unsupported class file major version 64

  java.lang.IllegalArgumentException: Unsupported class file major version 64
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199)
...
...
  1 error


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 718ms
```
Given that you have more experience, what would suggest to do? I hate wasting this time setting up the env, instead of actually coding... :(

Meanwhile I found this, I will watch it: https://www.youtube.com/watch?v=0NxYJgATevg

**Comment by Fabryz** [comment] 2023-11-21 15:40
Step forward: I went back to JDK17, added the "JAVA_HOME" env var on my `.zprofile`, then rebooted my mac.

Something is working because now at least it didn't show errors on "gradlew tasks", but said "BUILD SUCCESSFUL"
Then when I start the remote debugging:
- it said it build successfully
- it said it's uploading on the Quest 3
The progress bar finishes but then nothing else happens

![Screenshot 2023-11-21 alle 16 37 03](https://github.com/Nitwel/Immersive-Home/assets/17748/1aac4eb1-f1e4-4f0c-87cc-cf3621c5876e)
Exporting successfully
![Screenshot 2023-11-21 alle 16 37 13](https://github.com/Nitwel/Immersive-Home/assets/17748/12031ae6-a754-460a-81a6-2d4d0d442c50)
Building successfully
![Screenshot 2023-11-21 alle 16 37 17](https://github.com/Nitwel/Immersive-Home/assets/17748/42da9057-416d-4945-8a93-80ce16842d5d)
Installing...

I was expecting your app to be launching automatically 👀

**Comment by Fabryz** [comment] 2023-11-21 15:48
Ok so apparently the "Immersive Home" app appears in the "Quest 3 library" under "unknown source apps". 🎉 
If I launch it it tells me I need to grab my controllers and hit "continue".
I did that, the screen when black for one second and then I got back to the default Meta Home interface.

So I think maybe I'm finally building it correctly, the APK gets uploaded to the Quest 3, but for some reason it doesn't run 🤔

**Comment by Nitwel** [comment] 2023-11-21 17:58
Heya, I also ran into the problem of the app not opening a few times, unfortunately I don't exactly remember what the cause for that was exactly. I think it was related to the app failing when you start it or some materials missing.

Make sure you update https://github.com/Nitwel/Immersive-Home/blob/main/lib/home_adapters/hass_ws/hass.gd to use the correct url and token so the app can connect to HASS.

It can be helpful to export it using the remote debugger, sadly it is a bit buggy at the moment so you have to restart Godot each time you want to export in order for the debugger to work. Maybe that will give you a proper error message.

Also try pulling the latest changes from the testing branch and not main, maybe the main branch is broken at the moment.

**Comment by Nitwel** [comment] 2023-11-21 17:59
You can also try running it with F5 to see if it even starts up.

**Comment by Fabryz** [comment] 2023-11-21 18:22
> Heya, I also ran into the problem of the app not opening a few times, unfortunately I don't exactly remember what the cause for that was exactly. I think it was related to the app failing when you start it or some materials missing.
> 
> Make sure you update https://github.com/Nitwel/Immersive-Home/blob/main/lib/home_adapters/hass_ws/hass.gd to use the correct url and token so the app can connect to HASS.
> 
> It can be helpful to export it using the remote debugger, sadly it is a bit buggy at the moment so you have to restart Godot each time you want to export in order for the debugger to work. Maybe that will give you a proper error message.
> 
> Also try pulling the latest changes from the testing branch and not main, maybe the main branch is broken at the moment.

If the HASS url is empty would it generate issues that avoid the app to even load? I didn't edit anything and it actually starts up if I use the normal "Run project" play button. The issue only happens once uploaded to the actual headset

I will try the testing branch to see if anything changes

**Comment by Nitwel** [comment] 2023-11-24 11:05
Heya, I've spend the last couple days really polishing the stability and configuration functionallity so that others will be able to try it out against their HASS instance. (Before that, I just hardcoded the url and token as you might have seen).

For the near future, each release will also now have an official apk attached to it, so feel free to try that out too! https://github.com/Nitwel/Immersive-Home/releases/

**Comment by Fabryz** [comment] 2023-11-24 11:30
Thank you, I still didn't have time to test the "testing" branch.
I managed to make work only a "modified version" of the "Godot XR template" that a godot dev ZIPped and sent me via discord, only that project worked for me right away on the Quest 3 🤷 

Will try your new APK in the evening if I can, and then let you know

**Comment by Fabryz** [comment] 2023-12-11 11:30
> Will try your new APK **in the evening** if I can, and then let you know
The last famous words...

I did not forget about this, just life takes up a lot of time

**Comment by Nitwel** [comment] 2023-12-11 14:26
No worries 👍, gonna do a release later today with a lot of new features and improvements.

**Comment by Nitwel** [comment] 2023-12-11 16:08
Nevermind, no release today sadly. Something is broken with GitHub Actions causing the build to freeze infinitely. But Release v0.1.6 is usable too.

**Comment by Fabryz** [comment] 2023-12-14 10:34
@Nitwel I have just pulled the updates, checkouted the release v0.1.6 and ran a "Remote Debug" on the Quest 3:
it builds successfully, then uploads it on the device, but at the end nothing happens, I only see the default Meta environment.
If I go to my library and filter by "Unknown sources" (I always saw here the apps uploaded from the Godot IDE) there's no trace of the "Immersive home" app :/ 

I will now install SideQuest and try to manually sideload the built APK

**Comment by Fabryz** [comment] 2023-12-14 10:45
I've uploaded the APK via SideQuest, but I'm unable to see it anywhere. What am I doing wrong? :/

**Comment by Nitwel** [comment] 2023-12-14 11:30
That's very odd. After installing it through sidequest, it should at least show up somewhere. Maybe it is under the main app list as the same apk machtes the on in the Meta App Lab?

**Comment by Fabryz** [comment] 2023-12-14 14:11
> That's very odd. After installing it through sidequest, it should at least show up somewhere. Maybe it is under the main app list as the apk machtes the on in the Meta App Lab?

1- No, I've also searched manually on the search bar typing "immer..." but only another app appeared
2- I just saw that if I run it on the desktop, with the normal window debug, on "hands.gd" it gives me this error:
```
Parser Error: Could not find type "OpenXRHand" in the current scope.
```
I don't remember if I could debug it on the desktop, if I needed something else to run it
3- I will now discard my built APK, grab yours [from the github release](https://github.com/Nitwel/Immersive-Home/releases/tag/v0.1.6) sideload it and try again

**Comment by Fabryz** [comment] 2023-12-14 14:32
It worked! With your APK (v0.1.6) I finally managed to see your interface, so it was my faulty APK I guess due to that code error.
But why did it build it successfully in the first place? How can I solve that error on the previous comment?

Pay attention at that "Credits" window: a new one spawned every time I click on the text

**Comment by Nitwel** [comment] 2023-12-14 15:03
> How can I solve that error on the previous comment?

Which error do you mean exactly regarding that?
And yes that's part of the current implementation that I just spawn a credits window each time you click on it.

**Comment by Nitwel** [comment] 2024-01-04 11:30
I'll close this now as it seems this problem of having to build it yourself got more or less resolved by just providing prebuild apk's each version. Feel free to open another issue if you encounter more problems.

**Closed by Nitwel** 2024-01-04 11:30 UTC
Labels: question
